apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes-custom
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: hello-kubernetes-custom
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kubernetes-custom
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-kubernetes-custom
  template:
    metadata:
      labels:
        app: hello-kubernetes-custom
    spec:
      containers:
        - env:
            - name: MESSAGE
              value: Good Morning! This is version 1.0
          image: 'paulbouwer/hello-kubernetes:1.5'
          name: hello-kubernetes
          ports:
            - containerPort: 8080
